/*
READ THIS FIRST

Purpose:
A container that holds both Theme and GameRules, generated by the AI.

Why this file exists:
Provides a unified contract for the AI's structured output.

Learning Note:
Using a single JSON contract for both visuals and behavior ensures the AI's "vision"
for the game is applied consistently.
*/

namespace AISnakeGame.GameEngine;

public class GameConfiguration
{
    public Theme Theme { get; set; } = new();
    public GameRules Rules { get; set; } = new();
}
