name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Publish
        run: dotnet publish AISnakeStudio.csproj -c Release -o release

      - name: Fix Service Worker and Base Href
        run: |
          # Detect the repository name for the base href
          REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          sed -i "s/<base href=\"\/\" \/>/<base href=\"\/$REPO_NAME\/\" \/>/g" release/wwwroot/index.html

          # GitHub Pages requires a .nojekyll file to prevent Jekyll from processing WASM files
          touch release/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages
